### PR TITLE
Update variable calls to have the same response type & more

### PR DESCRIPTION
**Pull request by gcornut**
- Update variable calls to have the same response type
- Add documentation of the response type
- Remove 'variable by category' call & add the category parameter in the 'variable list' call
- Corrected fields name according to conventions.

[Related issue #12](https://github.com/plantbreeding/Documentation/issues/21)

### CODE REVIEW

**Comment by jeback1** [comment]
Hi Guillaume,
Thanks for making these updates.  Do you think we should keep the variables-harmonization branch for making other change or delete it?
Best regards,
Jan Erik

**Comment by jackeblagare** [comment]
We can delete it so that it will not become too big that it's hard to keep track of what's been happening. Our practice is that each branch is associated with a particular issue so that it's small enough to manage. We can also do that or maybe someone has a better idea.

**Comment by naymesh** [comment]
Cleanup: Deleting the branch now that it is pulled into master. We can restore if needed though I dont see we will need to do that.

**Comment by naymesh** [comment]
@jeback1  do we consider the change as part of V1 or is it for V2?

**Comment by gcornut** [comment]
Thank you for the merge
I have closed the related issues that were resolved by this pull request

**Comment by jeback1** [comment]
I consider this to be part of v 1
Cheers,
Jan Erik

**Pull request merged**
