### PR TITLE
proposal of call for trial stat results

### PR DESCRIPTION
**Pull request by j-alberto**

### CODE REVIEW

**Comment by j-alberto** [comment]
this call should be put into Trial's scope.

**Comment by jeback1** [comment]
Hi Jorge,
A couple of questions about your proposed call:
1) You have a StudyDbID key in the results with no value.  What is this key meant for?
2) The 'value' key; how does one know whether it is an average, median, or some other statisitc?
Best regards,
Jan Erik

**Comment by j-alberto** [comment]
1. StudyDbId with no value: is was a typing error, it should contain the study identifier to associate the results with. Since the results cannot be attached to a single plot, but to all plots with the same germplasm for a given study. 

2. To tell between average, std deviation, etc. We propose using observationVariableId, defining new variables with the same property(trait), and scale of the ones used for raw data , but using different methods: "statistical average", "statistical std deviation", etc. This way we can ask for either raw or statistical observations by specifying the variables we want. They will still be attached to the same trait and germplasm.

**Comment by j-alberto** [comment]
For a better support of single and multi study analysis results some changes need to be discussed.
1. To distinguish between single(study) and multi (trial) location analysis, it would be necessary to create a superset of levels in this call:  [/brapi/v1/observationLevels](https://github.com/plantbreeding/API/blob/master/Specification/Studies/ListObservationLevels.md) like : plant, plot, study entry, trial entry and germplasm.
2. Statistical observations need its own observation units with observationLevel=studyEntry|trialEntry. One new problem comes out here: currently there is no way to retrieve a list of germplasm at Trial Level, only at Study Level. Probably a new call for trials is needed, similar to [/brapi/v1/studies/{studyDbId}/germplasm](https://github.com/plantbreeding/API/blob/master/Specification/Studies/StudyGermplasmDetails.md)
3. The observation object can map to entries with the existing property **entryNumber**; plotNumber and plantNumber would be empty.

All of this is a preliminary approach which needs to be discussed, of course.

**Comment by BrapiCoordinatorSelby** [comment]
Moved to #499

**Pull request closed without merging**
